### ISSUE TITLE
Vendor page Changes

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#106]
- Make OurTreat logo larger.
- Logout button isn't working.
- Forgot password button not working

- After entering business name it should save and not be changeable by the company. This would prevent a disgruntled employee from creating havoc on the website. As such, "Company Name" would not be necessary. When clicking on the game, the "company name" input can be removed. That way it'll show the picture and then the item that is being give away, the company name, and address to redeem at.

- Game type: Will now be at the top of the input list.

**Comment by shreyansjain** [comment]
For now, can we postpone the change where we still use "Company Name"  when creating a game (maybe changing to Game Title). 
Reason is, by design, game (package) is a collection of games (irrespective of game_type), and the company_name is an attribute in each game of a package. It'll work fine for all games except for package game type since what company_name to use?

**Comment by EhJay22** [comment]
I see the point you're making, but if when doing the package perhaps Roberto can enter the company name as "(Company A) and (Company B) are giving away a package..."
