### ISSUE TITLE
countdown clock / My Games

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#121]
It's working, ish?

Can we make it centered over the image, and make the font 2-3x larger so it's really pronounced?

When the countdown clock was going, Roberto's stopped at 30~seconds and was counting down at 1/10th of the speed from there on on one test.

And when clicking on "My Games" it showed up as the bottom game instead  of the top game. Can it be moved so that a game that is in it's 1 minute countdown is at the top?

**Comment by shreyansjain** [comment]
I can make the font a bit bigger in the next build.
Yes, there was a calculation mistake in the timer, I have fixed it. And you'll see it working in the next build.

I'll look into it making the game with the timer on top.

From: EhJay22
Sent: Monday, April 30, 2018 5:53 PM
To: OurTreatApp/OurTreat-iOS
Reply To: OurTreatApp/OurTreat-iOS
Cc: Subscribed
Subject: [OurTreatApp/OurTreat-iOS] countdown clock / My Games (#121)



It's working, ish?

Can we make it centered over the image, and make the font 2-3x larger so it's really pronounced?

When the countdown clock was going, Roberto's stopped at 30~seconds and was counting down at 1/10th of the speed from there on on one test.

And when clicking on "My Games" it showed up as the bottom game instead of the top game. Can it be moved so that a game that is in it's 1 minute countdown is at the top?

**Comment by EhJay22** [comment]
Thanks

**Comment by shreyansjain** [comment]
![img_1268](https://user-images.githubusercontent.com/2359895/39460598-72aaeea4-4cb9-11e8-8075-a66497da46ec.PNG)

Looks good?

**Comment by EhJay22** [comment]
It's centered on the grid, but can it be centered on the picture?

**Comment by shreyansjain** [comment]
Oh, that might be tricky to implement and cannot guarantee, it would always be centered when used on different device sizes. 
The above will though

**Comment by EhJay22** [comment]
The countdown clock is going funky. When you click on it it's counting down by a 10th of a second, not per second.
