### ISSUE TITLE
Import Friends

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#187]
The import friends feature (done via a text message) is showing up under a separate screen and not on the Add Friends screen. This needs to be merged otherwise people will never find it.

**Comment by shreyansjain** [comment]
what do you mean?

From: EhJay22
Sent: Thursday, July 19, 2018 7:21 PM
To: OurTreatApp/OurTreat-iOS
Reply To: OurTreatApp/OurTreat-iOS
Cc: Subscribed
Subject: [OurTreatApp/OurTreat-iOS] Import Friends (#187)



The import friends feature (done via a text message) is showing up under a separate screen and not on the Add Friends screen. This needs to be merged otherwise people will never find it.

**Comment by EhJay22** [comment]
On the app. Click the 3 lines in the top corner. Click add friends. click import phone contacts. That is also where the texting invite friends thing should be

**Comment by EhJay22** [comment]
Thanks.
